### ISSUE TITLE
CloudFlare block from inside container 

### ISSUE THREAD

**Issue by udondan** [buanet/docker-iobroker#141] opened 2020-10-17 11:11 UTC
When I start ioBroker I see this error:

```
Cannot download json from http://download.iobroker.net/sources-dist-hash.json. Error: <html>
<head>
<title>The page is temporarily unavailable</title>
<style>
body { font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body bgcolor="white" text="black">
<table width="100%" height="100%">
<tr>
<td align="center" valign="middle">
The page you are looking for is temporarily unavailable.<br/>
Please try again later.
<br />
62aa1f6e33e2632b1b0232870aa785e4
f41aca8bb33d7ac21f8fb970d4c97ed8
de92204a0c899f566a516e316426c90e
</td>
</tr>
</table>
</body>
</html>
```

When accessing the URL myself I see my request is being blocked by CloudFlare.

```
# wget -S http://download.iobroker.net/sources-dist-hash.json
--2020-10-17 13:02:44--  http://download.iobroker.net/sources-dist-hash.json
Auflösen des Hostnamens download.iobroker.net (download.iobroker.net)… 79.143.182.215, 2a02:c205:0:855::1
Verbindungsaufbau zu download.iobroker.net (download.iobroker.net)|79.143.182.215|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet …
  HTTP/1.1 301 Moved Permanently
  Date: Sat, 17 Oct 2020 11:02:44 GMT
  Server: Apache/2.4.25 (Debian)
  Location: http://repo.iobroker.live/sources-dist-hash.json
  Content-Length: 343
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Content-Type: text/html; charset=iso-8859-1
Platz: http://repo.iobroker.live/sources-dist-hash.json [folgend]
--2020-10-17 13:02:44--  http://repo.iobroker.live/sources-dist-hash.json
Auflösen des Hostnamens repo.iobroker.live (repo.iobroker.live)… 172.67.180.22, 104.27.167.175, 104.27.166.175, ...
Verbindungsaufbau zu repo.iobroker.live (repo.iobroker.live)|172.67.180.22|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet …
  HTTP/1.1 520
  Date: Sat, 17 Oct 2020 11:02:44 GMT
  Content-Type: text/html; charset=UTF-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  Set-Cookie: cf_ob_info=520:5e398772bfe00bed:AMS; path=/; expires=Sat, 17-Oct-20 11:03:14 GMT
  Set-Cookie: cf_use_ob=80; path=/; expires=Sat, 17-Oct-20 11:03:14 GMT
  X-Frame-Options: SAMEORIGIN
  Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
  Expires: Thu, 01 Jan 1970 00:00:01 GMT
  CF-RAY: 5e398772bfe00bed-AMS
  Server: cloudflare
2020-10-17 13:02:44 FEHLER 520: (keine Beschreibung).
```

I'm posting this here, since I'm only facing this problem from inside the container. The same `wget` call is not blocked when ran directly from the host. Any idea what could be the cause?

**Comment by buanet** [comment] 2020-10-17 19:31
Hi,
where do you see the error? And when? Seems to be an issue when updating reop. 
I think this is not a container issue. Did you search at ioBroker forum for that?

Regards,
André

**Comment by udondan** [comment] 2020-10-18 09:52
Hi André,

this was happening on startup when attempting to update to the latest version via backup.

As written at the bottom, this was _only_ happening from inside the container, not from the parent host. Or in commands:

```bash
$ curl -o /dev/null --silent --head -L --write-out '%{http_code}\n' http://download.iobroker.net/sources-dist-hash.json
200

docker exec -it $(docker ps -qf "name=iobroker" | head -n 1) curl -o /dev/null --silent --head -L --write-out '%{http_code}\n' http://download.iobroker.net/sources-dist-hash.json
520
```

I have no idea how this could happen. To CloudFlare this should look like the same request. At least I thought so.  ¯\\_(ツ)\_/¯

Anyway. The import of the backup failed. Other than that above error, there was nothing suspicious in the logs. But the restored system was not working due to missing files. 

I then just reverted, did the upgrade in the container v4 and then swapped to v5 and did a `npm rebuild`. Haven't seen the problem since then. So feel free to just close.

Cheers,
Daniel

**Comment by buanet** [comment] 2020-10-18 20:45
Hi,
I was not able to reproduce the error. Sorry. 

> I then just reverted, did the upgrade in the container v4 and then swapped to v5 and did a npm rebuild

You can also set up a fresh iobroker container and do the restore manually using `iobroker restore` command.  

As the problem is gone after your upgrade, I close this issue. 

Regards,
André

**Closed by buanet** 2020-10-18 20:45 UTC
